config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  
  get 'welcome/index'

  devise_for :parents
  namespace :parents do
    root :to => "children#index"
    resources :timeline, only: :index do
      get 'save'
    end
    resources :children, only: [:index, :new, :create, :edit, :update] do
      resources :weekly_schedules, only: [:index] do
        resources :daily_schedules, only: [:show]
      end
    end
    resources :favorite_posts, only: :index
  end

  devise_for :caretakers
  namespace :caretakers do
    root :to => "posts#index"
    resources :posts, only: [:index, :new, :create, :edit, :update]
  end

  #post 'manager/programs/:program_id/weekly_schedules/:id/publish', to: 'manager/weekly_schedules#publish', as: 'publish_manager_program_weekly_schedule'
  namespace :manager do
    root :to => "programs#index"
    resources :programs, only: [:index, :new, :create, :edit, :update] do
      resources :weekly_schedules, only: [:index, :create, :publish] do
        post 'publish'
        resources :daily_schedules, only: [:edit] do
          resources :activities, only: [:new, :create, :edit, :update]
        end
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/views/welcome/index.html.erb
<div class="row d-flex justify-content-center">
  <h3>Welcome to Sunshine Daycare Site</h3>
</div>
<div class="row d-flex justify-content-center">
  <h1>Are you?</h1>
</div>
<div class="row d-flex justify-content-center">
  <%= link_to parents_root_path do %>
    <div class="cardbox cardbox-center cardbox-hover cardbox-small">
      <div><b>Parent</b></div>
    </div>
  <% end %>
  <%= link_to caretakers_root_path do %>
  <div class="cardbox cardbox-center cardbox-hover cardbox-small">
    <div><b>Caretaker</b></div>
  </div>
  <% end %>
  <%= link_to manager_programs_path do %>
    <div class="cardbox cardbox-center cardbox-hover cardbox-small">
      <div><b>Manager</b></div>
    </div>
  <% end %>
</div>