config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  
  get 'welcome/index'

  devise_for :parents
  namespace :parents do
    root :to => "children#index"
    resources :timeline, only: :index do
      get 'save'
    end
    resources :children, only: [:index, :new, :create, :edit, :update] do
      resources :weekly_schedules, only: [:index] do
        resources :daily_schedules, only: [:show]
      end
    end
    resources :favorite_posts, only: :index
  end

  devise_for :caretakers
  namespace :caretakers do
    root :to => "posts#index"
    resources :posts, only: [:index, :new, :create, :edit, :update]
  end

  #post 'manager/programs/:program_id/weekly_schedules/:id/publish', to: 'manager/weekly_schedules#publish', as: 'publish_manager_program_weekly_schedule'
  namespace :manager do
    root :to => "programs#index"
    resources :programs, only: [:index, :new, :create, :edit, :update] do
      resources :weekly_schedules, only: [:index, :create, :publish] do
        post 'publish'
        resources :daily_schedules, only: [:edit] do
          resources :activities, only: [:new, :create, :edit, :update]
        end
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :daily_schedule
  belongs_to :caretaker
  validates :name, :start_time, :end_time, :location, :category, :presence => true
  validates :end_time, after_date: :start_time

  enum location: ['Room A', 'Room B', 'Room C', 'Library', 'Playground', 'Garden', 'West Garden', 'Outbound']
  enum category: ['Meal', 'Cooking', 'Social', 'Outdoor', 'Reading', 'English', 'Lecture', 'Other']
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def new
    @program = Program.find(params[:program_id])
    @weekly_schedule = @program.weekly_schedules.find(params[:weekly_schedule_id])
    @daily_schedule = DailySchedule.find(params[:daily_schedule_id])
    @activity = @daily_schedule.activities.new(:start_time=>@daily_schedule.date, :end_time=>@daily_schedule.date)
  end

  def create
    @program = Program.find(params[:program_id])
    @weekly_schedule = @program.weekly_schedules.find(params[:weekly_schedule_id])
    @daily_schedule = DailySchedule.find(params[:daily_schedule_id])
    @activity = @daily_schedule.activities.new(activity_params)

    if @activity.save
      redirect_to edit_program_weekly_schedule_daily_schedule_path(@program, @daily_schedule.weekly_schedule, @daily_schedule)
    else
      render 'new'
    end
  end

  def edit
    @program = Program.find(params[:program_id])
    @weekly_schedule = @program.weekly_schedules.find(params[:weekly_schedule_id])
    @daily_schedule = DailySchedule.find(params[:daily_schedule_id])
    @activity = Activity.find(params[:id])
  end

  def update
    @program = Program.find(params[:program_id])
    @weekly_schedule = @program.weekly_schedules.find(params[:weekly_schedule_id])
    @daily_schedule = DailySchedule.find(params[:daily_schedule_id])
    @activity = Activity.find(params[:id])

    if @activity.update(activity_params)
      redirect_to edit_program_weekly_schedule_daily_schedule_path(@program, @daily_schedule.weekly_schedule, @daily_schedule)
    else
      render 'edit'
    end
  end

  private

  def activity_params
    params.require(:activity).permit(:name, :location, :category, :start_time, :end_time)
  end
end

app/controllers/manager/activities_controller.rb
class Manager::ActivitiesController < ManagerController 
  def new
    @program = Program.find(params[:program_id])
    @weekly_schedule = @program.weekly_schedules.find(params[:weekly_schedule_id])
    @daily_schedule = DailySchedule.find(params[:daily_schedule_id])
    @activity = @daily_schedule.activities.new(:start_time=>@daily_schedule.date, :end_time=>@daily_schedule.date)
  end

  def create
    @program = Program.find(params[:program_id])
    @weekly_schedule = @program.weekly_schedules.find(params[:weekly_schedule_id])
    @daily_schedule = DailySchedule.find(params[:daily_schedule_id])
    @activity = @daily_schedule.activities.new(activity_params)

    if @activity.save
      redirect_to edit_manager_program_weekly_schedule_daily_schedule_path(@program, @daily_schedule.weekly_schedule, @daily_schedule)
    else
      render 'new'
    end
  end

  def edit
    @program = Program.find(params[:program_id])
    @weekly_schedule = @program.weekly_schedules.find(params[:weekly_schedule_id])
    @daily_schedule = DailySchedule.find(params[:daily_schedule_id])
    @activity = Activity.find(params[:id])
  end

  def update
    @program = Program.find(params[:program_id])
    @weekly_schedule = @program.weekly_schedules.find(params[:weekly_schedule_id])
    @daily_schedule = DailySchedule.find(params[:daily_schedule_id])
    @activity = Activity.find(params[:id])

    if @activity.update(activity_params)
      redirect_to edit_manager_program_weekly_schedule_daily_schedule_path(@program, @daily_schedule.weekly_schedule, @daily_schedule)
    else
      render 'edit'
    end
  end

  private

  def activity_params
    params.require(:activity).permit(:caretaker_id, :name, :location, :category, :start_time, :end_time)
  end
end

app/views/activities/_form.html.erb
<%= simple_form_for [@program,@weekly_schedule,@daily_schedule,@activity] do |f| %>
  <%= f.input :name %>
  <%= f.input :location, collection: Activity.locations.keys %>
  <%= f.input :category, collection: Activity.categories.keys %>
  <%= f.input :start_time %>
  <%= f.input :end_time %>
  <%= f.button :submit, class: 'btn btn-primary'  %>
<% end %>

app/views/activities/_list.html.erb
<%= link_to "Add new activity", new_program_weekly_schedule_daily_schedule_activity_path(@program, @weekly_schedule, @daily_schedule), class:"btn btn-primary float-right"%>
<h4>Activities</h4>
<% @daily_schedule.activities.order(:start_time).where.not(id: nil).each do |activity| %>
  <%= link_to edit_program_weekly_schedule_daily_schedule_activity_path(@program, @weekly_schedule, @daily_schedule, activity) do%>
    <div class="cardbox cardbox-block <%= 'cardbox-active' if @activity == activity %>">
      <div><%= activity.start_time.strftime('%I:%M%p') %> - <%= activity.end_time.strftime('%I:%M%p') %></div>
      <div><b><%= activity.name %></b></div>
      <div><%= activity.category %></div>
      <div>at <%= activity.location %></b></div>
    </div>
  <% end %>
<% end %>

app/views/activities/edit.html.erb
<%= render 'weekly_schedules/heading' %>
<hr>
<div class="clearfix">
  <div class="row d-flex justify-content-center">
    <%= render 'daily_schedules/list' %>
  </div>
  <br>
  <div class="row">
    <div class="col-lg-6 right-border">
        <%= render 'list' %>
    </div>
    <div class="col-lg-6">
      <div class="new-activity-form">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/activities/new.html.erb
<%= render 'weekly_schedules/heading' %>
<hr>
<div class="clearfix">
  <div class="row d-flex justify-content-center">
    <%= render 'daily_schedules/list' %>
  </div>
  <br>
  <div class="row">
    <div class="col-lg-6 right-border">
      <%= render 'list' %>
    </div>
    <div class="col-lg-6">
      <div class="new-activity-form">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>